# coding = utf-8 
# Mapping rules used to map table's data, topics are used to evaluatefunctions with same name.

MAPPING_RULES_IT={'MPG': 'minutesPerGame', 
'GS': 'gamesStarted', 
'Squadra': 'team', 
'BPG': 'blockPerGame', 
'GP': 'gamesPlayed', 
'RPG': 'reboundsPerGame', 
'Year': 'Year', 
'Stagione regolare': 'regularSeason', 
'3P%': 'threePoints', 
'Anno': 'year', 
'Campion.': 'championship', 
'FT%': 'freeThrow', 
'Stagione': 'season', 
'Team': 'team', 
'FG%': 'fieldGoal', 
'PPG': 'pointPerGame', 
'APG': 'assistsPerGame', 
'SPG': 'stealsPerGame'}


MAPPING_RULES_EN={'Regular season_Team': 'team', 
'MIN': 'min', 
'Ramone Moore': 'matches', 
'Regular season_GS': 'gamesStarted', 
'Regular season_GP': 'gamesPlayed', 
'Head coaching record_Result': 'result', 
'Kentucky statistics_FG%': 'fieldGoal', 
'Playoffs_FT%': 'freeThrow', 
'Regular season_MPG': 'minutesPerGame', 
'College statistics_APG': 'assistsPerGame', 
'Playoffs_FG%': 'fieldGoal', 
'College statistics_Year': 'Year', 
'Playoffs_Team': 'team', 
'Regular season_3P%': 'threePoints', 
'SPG': 'stealsPerGame', 
'League': 'league', 
'Kentucky statistics_3P%': 'threePoints', 
'GS': 'gamesStarted', 
'GP': 'gamesPlayed', 
'Kentucky statistics_BPG': 'blockPerGame', 
'College statistics_FT%': 'freeThrow', 
'College statistics': 'college', 
'Regular season': 'regularSeasonMatch', 
'College statistics_RPG': 'reboundsPerGame', 
'FG%': 'fieldGoal', 
'Regular season_APG': 'assistsPerGame', 
'Kentucky statistics_Team': 'team', 
'Regular season_PPG': 'pointPerGame', 
'Head coaching record_Year': 'Year', 
'Competition': 'Competition', 
'Playoffs_Year': 'Year', 
'Regular season_RPG': 'reboundsPerGame', 
'Regular season_FT%': 'freeThrow', 
'Regular season_SPG': 'stealsPerGame', 
'APG': 'assistsPerGame', 
'Playoffs_RPG': 'reboundsPerGame', 
'Regular season_FG%': 'fieldGoal', 
'BPG': 'blockPerGame', 
'Playoffs_MPG': 'minutesPerGame', 
'Playoffs_SPG': 'stealsPerGame', 
'Playoffs_3P%': 'threePoints', 
'Head coaching record_Team': 'team', 
'Regular season_Year': 'Year', 
'Opponent': 'opponent', 
'College statistics_FG%': 'fieldGoal', 
'Kentucky statistics_FT%': 'freeThrow', 
'PPG': 'pointPerGame', 
'Regular season_BPG': 'blockPerGame', 
'Season': 'season', 
'Playoffs_APG': 'assistsPerGame', 
'Playoffs_BPG': 'blockPerGame', 
'FT%': 'freeThrow', 
'RPG': 'reboundsPerGame', 
'College statistics_GS': 'gamesStarted', 
'College statistics_GP': 'gamesPlayed', 
'Age': 'age', 
'Kentucky statistics_Year': 'Year', 
'College statistics_MPG': 'minutesPerGame', 
'Kentucky statistics_APG': 'assistsPerGame', 
'College statistics_BPG': 'blockPerGame', 
'Kentucky statistics_PPG': 'pointPerGame', 
'Kentucky statistics_GP': 'gamesPlayed', 
'Team': 'team', 
'Kentucky statistics_RPG': 'reboundsPerGame', 
'Playoffs_GP': 'gamesPlayed', 
'Playoffs_GS': 'gamesStarted', 
'College statistics_Team': 'team', 
'MPG': 'minutesPerGame', 
'Kentucky statistics_SPG': 'stealsPerGame', 
'College statistics_PPG': 'pointPerGame', 
'Tournament': 'Tournament', 
'College statistics_3P%': 'threePoints', 
'College statistics_SPG': 'stealsPerGame', 
'Playoffs_PPG': 'pointPerGame', 
'Result': 'result', 
'Year': 'Year', 
'3P%': 'threePoints'}


