# coding:utf-8 
# Mapping rules used to map table's data, topics are used to evaluate functions with same name.

MAPPING_RULES_IT={'Cronologia completa delle presenze e dei punti in Nazionale - Italia - Risultato': 'result', 
'Squadra': 'team', 
'SECTION_Nazionale': 'national', 
'Statistiche tiro - Tiri da 2': 'twoPoints', 
'DIF': 'difensive', 
'Altre statistiche - Assist': 'assistsPerGame', 
'Anno': 'year', 
'Statistica': 'statisticsRecord', 
'Statistiche - V-P%': 'winLoss', 
'Cronologia completa delle presenze e dei punti in Nazionale - Stati Uniti - Data': 'date', 
'OFF': 'offensive', 
'Cronologia completa delle presenze e dei punti in Nazionale - Stati Uniti - Ospiti': 'visiting', 
'SECTION_Regular season': 'regularSeason', 
'Cronologia completa delle presenze e dei punti in Nazionale - Italia - Citt.': 'town', 
'Statistiche - Lega': 'division', 
'Cronologia completa delle presenze e dei punti in Nazionale - Italia - In casa': 'home', 
'PPG': 'pointsPerGame', 
'SPP': 'spp', 
'Altre statistiche - Rimb.': 'reboundsPerGame', 
'Statistiche - P': 'loss', 
'Statistiche - V': 'wins', 
'Cronologia completa delle presenze e dei punti in Nazionale - Italia - Punti': 'points', 
'Statistiche tiro - Tiri da 3': 'threePoints', 
'Campion.': 'championship', 
'FT%': 'freeThrow', 
'PG': 'playoffGames', 
'RPG': 'reboundsPerGame', 
'Altre statistiche - Stopp.': 'blockPerGame', 
'NBA': 'nba', 
'SECTION_NCAA': 'ncaa', 
'SECTION_Cronologia recente presenze e punti in Nazionale': 'statistics', 
'SECTION_Cronologia presenze e punti in Nazionale': 'national', 
'SECTION_Lega NEBL': 'nebl', 
'Cronologia completa delle presenze e dei punti in Nazionale - Italia - Note': 'notes', 
'Cronologia completa delle presenze e dei punti in Nazionale - Italia - Competizione': 'championship', 
'Cronologia completa delle presenze e dei punti in Nazionale - Stati Uniti - Punti': 'points', 
'Cronologia completa delle presenze e dei punti in Nazionale - Stati Uniti - In casa': 'home', 
'RPP': 'rpp', 
'Cronologia completa delle presenze e dei punti in Nazionale - Italia - Ospiti': 'visiting', 
'SECTION_Stagione regolare': 'regularSeason', 
'Cronologia completa delle presenze e dei punti in Nazionale - Stati Uniti - Risultato': 'result', 
'PPP': 'ppp', 
'Statistiche tiro - Liberi': 'freeThrow', 
'MPP': 'mpp', 
'Team': 'team', 
'FG%': 'fieldGoal', 
'APG': 'assistsPerGame', 
'PRPP': 'prpp', 
'Cronologia completa delle presenze e dei punti in Nazionale - Stati Uniti - Citt.': 'town', 
'Partite - Pres.': 'gamesPlayed', 
'MPG': 'minutesPerGame', 
'SECTION_Playoff': 'playoff', 
'SECTION_Record individuali': 'individualRecord', 
'SECTION_Playoffs': 'playoff', 
'PRPG': 'prpg', 
'SPG': 'stolePerGame', 
'APP': 'app', 
'Altre statistiche - Rubate': 'stealsPerGame', 
'SECTION_Basketligan': 'basketligan', 
'Altre statistiche - Punti': 'pointsPerGame', 
'Cronologia completa delle presenze e dei punti in Nazionale - Italia - Data': 'date', 
'Cronologia completa delle presenze e dei punti in Nazionale - Stati Uniti - Competizione': 'championship', 
'TL%': 'tl', 
'Partite - Minuti': 'minutesPerGame', 
'Statistiche - G': 'games', 
'Stagione': 'season', 
'Year': 'Year', 
'SECTION_Statistiche': 'statistics', 
'PI': 'performanceIndex', 
'Cronologia completa delle presenze e dei punti in Nazionale - Stati Uniti - Note': 'notes', 
'Partite - Titol.': 'gamesStarted', 
'3P%': 'threePoints', 
'SECTION_Presenze e punti nei club': 'statistics'}


MAPPING_RULES_EN={'GS': 'gamesStarted', 
'Conference': 'conference', 
'Points:': 'pointsPerGame', 
'W': 'gamesWin', 
'SECTION_Euroleague': 'league', 
'MIN': 'min', 
'Hometown': 'town', 
'SECTION_NBL': 'nbl', 
'REB': 'reboundsPerGame', 
'SECTION_High school career': 'highSchoolCareer', 
'SECTION_NBA': 'nba', 
'Free Throws:': 'freeThrow', 
'SECTION_Eurocup': 'euroCup', 
'NBL career:': 'nblCareer', 
'Finish': 'gamesFinished', 
'W.L%': 'winLoss', 
'AST': 'assistsPerGame', 
'SECTION_Ramone Moore': 'statistics', 
'Points': 'pointsPerGame', 
'Overall': 'overall', 
'Assists:': 'assistsPerGame', 
'Rebounds:': 'reboundsPerGame', 
'High school / college': 'collegeName', 
'SECTION_Domestic leagues': 'league', 
'PF': 'pf', 
'PIR': 'performanceIndex', 
'FGA': 'fga', 
'SPG': 'stolePerGame', 
'League': 'nameLeague', 
'SECTION_CBA': 'cba', 
'OFF': 'offensive', 
'RPG': 'reboundsPerGame', 
'GP': 'gamesPlayed', 
'Steals:': 'stealsPerGame', 
'L': 'gamesLost', 
'SECTION_Head coaching record': 'headCoaching', 
'FG%': 'fieldGoal', 
'SECTION_College statistics': 'collegeStatistics', 
'SECTION_Honour roll': 'honourRoll', 
'SECTION_EuroLeague': 'league', 
'3PM': '3pm', 
'SECTION_Louisiana Tech statistics': 'statistics', 
'Height': 'height', 
'3 Points:': 'threePoints', 
'College': 'nameCollege', 
'Adelaide 36ers Club MVP:': 'adelaideMVP', 
'SECTION_Kentucky statistics': 'statistics', 
'APG': 'assistsPerGame', 
'Postseason': 'postseason', 
'Standing': 'standind', 
'NBL Grand Final appearances:': 'nblGrandFinal', 
'All-NBL First Team:': 'nblFirstTeam', 
'BPG': 'blocksPerGame', 
'TOV': 'tov', 
'Games:': 'games', 
'FGM': 'fgm', 
'3PA': '3pa', 
'SECTION_Duke statistics': 'statistics', 
'Commit date': 'commitDate', 
'SECTION_Regular season': 'regularSeason', 
'DEF': 'defensive', 
'SECTION_International statistics': 'statistics', 
'SECTION_Vanderbilt statistics': 'statistics', 
'SECTION_College': 'collegeStatistics', 
'PW': 'playoffWins', 
'Season': 'season', 
'STL': 'stolePerGame', 
'SECTION_NBL career stats': 'nbl', 
'FT%': 'freeThrow', 
'PG': 'playoffGames', 
'NBL Championships:': 'nblChampionships', 
'Rebounds per game': 'reboundsPerGame', 
'Assists per game': 'assistsPerGame', 
'PTS': 'pointsPerGame', 
'PL': 'playoffLosses', 
'Field Goals:': 'fieldGoal', 
'Name': 'Name', 
'G': 'games', 
'NBL All-Star Game:': 'nblAllStarGame', 
'NBL Grand Final MVP:': 'nblGrandFinalMVP', 
'Age': 'age', 
'Year': 'Year', 
'FTA': 'fta', 
'SECTION_Statistics': 'statistics', 
'BLK': 'blocksPerGame', 
'Team': 'team', 
'PPG': 'pointsPerGame', 
'Blocks:': 'blocksPerGame', 
'FTM': 'ftm', 
'Points per game': 'pointsPerGame', 
'MPG': 'minutesPerGame', 
'SECTION_Playoffs': 'playoff', 
'Weight': 'weight', 
'NBL Finals appearances:': 'nblFinals', 
'Tournament': 'Tournament', 
'SECTION_Head Coaching Record': 'headCoaching', 
'Result': 'result', 
'PW.L%': 'playoffWinsLoss', 
'3P%': 'threePoints'}


